version: "3.9" # optional since v1.27.0
services:
  api:
    build:
      context: ./apps/api
      target: production
      dockerfile: Dockerfile
    command: npm run start
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PG_HOST=${POSTGRES_HOST}
      - PG_PORT=${POSTGRES_PORT}
      - PG_DB_NAME="quickpaste"
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_BUCKET_NAME="quickpaste"
      - AWS_REGION="eu-central-1"
      - NODE_ENV="production"
  auth:
    build:
      context: ./apps/auth
      dockerfile: Dockerfile
      target: production
    command: npm run start
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - PG_HOST=${POSTGRES_HOST}
      - PG_PORT=${POSTGRES_PORT}
      - PG_DB_NAME="quickpaste"
      - NODE_ENV="production"
  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
      target: production
    command: npm run start
    volumes:
      - ./.yalc-store:/yalc:rw
    environment:
      - NUXT_HOST=0
      - PORT=3000
      - INTERNAL_GATEWAY_ADDRESS="http://gateway:80"
      - INTERNAL_API_ADDRESS="http://api:3000"
      - AUTH_SERVICE_ADDRESS="http://auth:3000"
      - WEB_ADDRESS=${WEB_DOMAIN_NAME}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - NODE_ENV="production"
  gateway:
    build:
      context: ./apps/gateway
      dockerfile: Dockerfile
      target: production
    volumes:
      - ./test:/etc/letsencrypt/
    environment:
      - DOMAIN_NAME=${WEB_DOMAIN_NAME}
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
      - auth
  maintainer:
    build:
      context: ./apps/maintainer
      dockerfile: Dockerfile
    depends_on:
      - api
    volumes:
      - ./letsencrypt:/etc/letsencrypt:rw
    environment:
      - DOMAIN_NAME=${WEB_DOMAIN_NAME}
      - EMAIL=${HELP_EMAIL}
