name: Deploy

on:
  push:
    branches: [ "release" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

jobs:
  build:
    runs-on: [self-hosted, linux]
    strategy:
      matrix:
        node-version: [22.14.0]
    
    env:
      CI: true

    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
      with:
        version: 10
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Prepare for build
      run: make prod-prepare-build
    - name: Setup enviroment and install deps
      run: pnpm add -g yalc && pnpm add -g workspace-to-yalc && pnpm install --shamefully-hoist && mkdir -p /var/letsencrypt/challange && mkdir -p /var/letsencrypt/certs
    - name: Build docker images
      run: make prod-build
  run:
    runs-on: [self-hosted, linux]
    needs: [build]
    steps:
      - name: Start containers
        run: make prod-up
